### ISSUE TITLE
Please list all dependencies

### ISSUE THREAD

**Issue by haochenuw** [schoppmp/linreg-mpc#2]
To make it possible to use this library, could you please list all dependencies. Based on my experience today it at least requires sodium and czmq, which weren't installed.

**Comment by schoppmp** [comment]
Thanks for bringing this up!
I pushed a commit that removes two executables that are no longer needed, which should get rid of the dependency on czmq and sodium. All other dependencies should now be listed in README.md.
Does this resolve the issue or are there any other dependencies that I overlooked?

**Comment by haochenuw** [comment]
It works now. Thanks a lot！
