### ISSUE TITLE
compiling and using new .oc files.

### ISSUE THREAD

**Issue by haochenuw** [schoppmp/linreg-mpc#4]
I realize this is a really silly question: I have written a file called QR.oc that contains a function which does QR factorization of a matrix. What do I need to do in order to use the function? I figured something needs to be change in the Makefile...but I don't know how to do it.  Could you give some instructions? Thanks!

**Comment by haochenuw** [comment]
Update: I tried putting the function qr() inside cholesky.oc and compiled it. It went through. But I still get undeclared function error when I try to call execYaoProtocol with qr.... any help would be appreciated!

**Comment by schoppmp** [comment]
Please have a look at the [examples](https://github.com/samee/obliv-c/tree/obliv-c/test/oblivc) that come with Obliv-C. For instance, the [Hamming example](https://github.com/samee/obliv-c/tree/obliv-c/test/oblivc/hamming) consists of three files. One `.h` file that declares the function `void hammingDistance(void* args)`, one `.oc` file that defines it and one `.c` file that includes the `.h` file and contains the main function.
If you stick to this pattern, everything should compile just fine. From the description of your error it sounds like you forgot to include the header file, but I would need to see your source code to be sure. I hope this helps.

**Comment by haochenuw** [comment]
I got it to work. Thanks!
