### ISSUE TITLE
question on aggregation results

### ISSUE THREAD

**Issue by haochenuw** [schoppmp/linreg-mpc#5]
I am toggling the input matrix X in readme_example.in, but it does not seem to give correct result A = X^TX . Could you let me know where I messed up? 
My .in file now looks like
4 4 2
localhost:1234
localhost:1235
localhost:1236 0
localhost:1237 2
4 4
5.0 1.0 4.0 1.0
3.0 0.0 1.0 1.0
1.0 1.0 1.0 0.0
2.0 2.0 3.0 4.0
4
1 2 3 4

.... I ran the following command: 
`for party in {1..4}; do bin/main examples/readme_example.in 56 $party cholesky 0 0 & done`

Since X has integer entries, I am expecting A to have integer entries too, but I saw this : 

![screenshot from 2017-04-04 15-23-47](https://cloud.githubusercontent.com/assets/4164808/24681575/b76b61a2-194a-11e7-87c6-a0b5d433b3df.png)

so it seems both A and b are non-integral. Is there some normalization I did not know? Please let me know. Thank you!

**Comment by schoppmp** [comment]
Yes, we do some normalization of the inputs. More specifically, `A = (X^T·X) / (n·d)`, where `n` and `d` are the input dimensions. So in your case, if you multiply your result by 16, you get what you were expecting.
Note that we also generally assume that the columns of the inputs are normalized to have mean `0` and variance `1`. For details, see [section 4.3 in the paper](https://eprint.iacr.org/2016/892.pdf#subsection.1.4.3).

**Comment by haochenuw** [comment]
Thanks! I have an additional question though. I tried to disable the normalization by setting the flag to false in the functions read_matrix and 
read_vector from run_party, but then all matrices become zero. My modification is below: 

![screenshot from 2017-04-05 13-28-55](https://cloud.githubusercontent.com/assets/4164808/24725445/d5a9e846-1a03-11e7-9775-9aeaf9bdded8.png)

Then I ran the same command,  but I got all zeros, and the result becomes the zero vector. 
![screenshot from 2017-04-05 13-32-39](https://cloud.githubusercontent.com/assets/4164808/24725599/65947566-1a04-11e7-9ab7-cc3bc1c967d6.png)

Did I mess up somewhere? Please help...

**Comment by schoppmp** [comment]
We use the normalize feature for two things: one is scaling of the inputs, and the other is re-scaling as part of the fixed-point multiplication, which needs to be done in advance to avoid overflows.
In your case, just changing the `normalizer` variable to `sqrt(pow(2,precision))` should work.

**Comment by haochenuw** [comment]
Ah I see! Thanks so much!
