### ISSUE TITLE
Necessity of editing the Makefile when adding new functions

### ISSUE THREAD

**Issue by haochenuw** [schoppmp/linreg-mpc#7]
I was wondering if it's necessary to change the Makefile if we want to add more functions? I see in the makefile now there is 
$(call obliv,cgd) 
which corresponds to the cgd function. If I have a new function in 
myfunc.oc, do I need to add $(call obliv,myfunc) accordingly? It seems to compile without adding, that's why I ask. Thanks!

**Comment by schoppmp** [comment]
The `native`/`obliv`/`both` functions are used to distinguish between object files compiled with `oblivcc` and those compiled with `$(CC)`.  
This isn't needed for all applications, and there are probably better ways to do this, so if you find one that is nicer and works with all the existing binaries, I'm happy to accept pull requests.

**Comment by schoppmp** [comment]
I rewrote the Makefile. Now, to add a new binary target, just create the corresponding .c file in `src/cmd`.
